// Generated by CoffeeScript 1.12.4
exports.initCommands = function() {
  return {
    lab: function() {
      return require("./cli");
    },
    repl: function() {
      return require("./repl");
    }
  };
};
