// Generated by CoffeeScript 1.12.4
var coffee, createModule, didExit, fs, isDev, isNodeJS, path, rimraf, sync, template, vm;

isNodeJS = require("isNodeJS");

didExit = require("didExit");

coffee = require("coffee-script");

rimraf = require("rimraf");

isDev = require("isDev");

path = require("path");

sync = require("sync");

fs = require("fsx");

vm = require("vm");

template = fs.readFile(path.resolve(__dirname + "/../src/template.coffee"));

module.exports = function(entry, options) {
  var absolutes, entryDir, error, id, mapRef, outDir, output, relatives, script;
  if (options == null) {
    options = {};
  }
  if (!fs.isFile(entry)) {
    throw Error("Must provide a file path: '" + entry + "'");
  }
  entryDir = path.dirname(entry);
  outDir = path.resolve(entryDir, "tmp");
  while (true) {
    id = Random.id(6);
    if (!fs.exists(path.join(outDir, id + ".coffee"))) {
      break;
    }
  }
  relatives = {};
  sync.each(["coffee", "js", "map"], function(ext) {
    return relatives[ext] = id + "." + ext;
  });
  absolutes = sync.map(relatives, function(filePath) {
    return path.join(outDir, filePath);
  });
  mapRef = log.ln + "//# sourceMappingURL=" + relatives.map + log.ln;
  script = fs.readFile(entry).trim().split(log.ln).join(log.ln + "    ");
  script = ["__dirname = \"" + (path.dirname(absolutes.js)) + "\"", "__filename = \"" + absolutes.js + "\"", template.replace(/\$SCRIPT/g, script)].join(log.ln);
  log.cyan(script);
  try {
    output = coffee.compile(script, {
      bare: true,
      sourceMap: true,
      sourceRoot: ".",
      sourceFiles: [relatives.coffee],
      generatedFile: relatives.js,
      filename: absolutes.coffee
    });
  } catch (error1) {
    error = error1;
    printSyntaxError(error, entry);
    log.moat(1);
    return false;
  }
  fs.writeDir(outDir);
  fs.writeFile(absolutes.coffee, script);
  fs.writeFile(absolutes.js, output.js + mapRef);
  fs.writeFile(absolutes.map, output.v3SourceMap);
  didExit(function() {
    log.moat(1);
    log.red("EXIT");
    log.moat(1);
    if (options.preservePaths !== true) {
      sync.each(absolutes, function(path) {
        return rimraf.sync(path);
      });
    }
  });
  log.pushIndent(2);
  log.moat(1);
  log.white("lotus-lab ");
  log.green(id);
  log.moat(0);
  log.yellow(path.relative(lotus.path, entry));
  log.moat(1);
  log.popIndent();
  global.lotus = lotus;
  global.sync = sync;
  define(global, {
    isDev: isDev,
    isNodeJS: isNodeJS,
    process: process,
    log: log,
    Promise: Promise
  });
  global.__module = makeModule(entry, module);
  vm.runInThisContext("try { global.__module.require('" + absolutes.js + "') } catch(error) { console.log('caught error!'); process.exit(0) }");
  return true;
};

createModule = (function() {
  var Module;
  Module = require("module");
  return function(modPath, parent) {
    var mod;
    mod = new Module(modPath, parent);
    mod.filename = modPath;
    mod.dirname = path.dirname(modPath);
    return mod;
  };
})();
